version: "3.8"

services:
  # PostgreSQL Database
  database:
    image: postgres:16-alpine
    container_name: househub-database
    environment:
      POSTGRES_DB: HouseHubApiDb
      POSTGRES_USER: househub_user
      POSTGRES_PASSWORD: househub_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - househub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U househub_user -d HouseHubApiDb"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: househub-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - DbSettings__ConnectionString=Host=database;Port=5432;Database=HouseHubApiDb;Username=househub_user;Password=househub_password;
      - CORS__AllowedOrigins=http://localhost:4200,http://frontend:80
    ports:
      - "5000:8080"
    volumes:
      - ./backend/logs:/app/logs # Application logs accessible from host
      - uploads_temp:/app/temp # Temporary file processing
      - backend_config:/app/config # Configuration files persistence
    depends_on:
      database:
        condition: service_healthy
    networks:
      - househub-network
    restart: unless-stopped

  # Frontend (Angular)
  frontend:
    build:
      context: ./house_hub_fea
      dockerfile: Dockerfile
      target: development
    container_name: househub-frontend
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "4200:4200"
    volumes:
      - ./house_hub_fea/src:/app/src:cached # Hot reload for development
      - ./house_hub_fea/angular.json:/app/angular.json:cached
      - ./house_hub_fea/package.json:/app/package.json:cached
      - ./house_hub_fea/tsconfig.json:/app/tsconfig.json:cached
      - ./house_hub_fea/tsconfig.app.json:/app/tsconfig.app.json:cached
      - ./house_hub_fea/tsconfig.spec.json:/app/tsconfig.spec.json:cached
      - ./house_hub_fea/node_modules:/app/node_modules:cached # Mount node_modules from host
      - frontend_dist:/app/dist # Build output persistence
    depends_on:
      - backend
    networks:
      - househub-network
    restart: unless-stopped

  # Frontend Production Build
  frontend-prod:
    build:
      context: ./house_hub_fea
      dockerfile: Dockerfile
      target: production
    container_name: househub-frontend-prod
    environment:
      - API_URL=http://localhost:5000
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - househub-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data: # PostgreSQL database persistence
  uploads_temp: # Temporary file processing
  backend_config: # Backend configuration files
  frontend_dist: # Frontend build output

networks:
  househub-network:
    driver: bridge
